[package]
name = "prs-cli"
version = "0.1.0"
authors = ["Tim Visee <3a4fb3964f@sinenomine.email>"]
license = "GPL-3.0"
readme = "README.md"
# homepage = "https://timvisee.com/projects/prs"
repository = "https://gitlab.com/timvisee/prs"
description = "Secure, fast & convenient password manager CLI with GPG & git sync"
keywords = ["pass", "passwordstore"]
categories = [
    "authentication",
    "command-line-utilities",
    "cryptography",
]
edition = "2018"

[badges]
gitlab = { repository = "timvisee/prs", branch = "master" }

[dependencies]
anyhow = "1.0"
chbs = "0.0.10"
clap = "2.33"
colored = "2.0"
derive_builder = "0.9"
edit = "0.1"
libc = "0.2"
notify-rust = "4.0"
prs-lib = { path = "../lib" }
shellexpand = "2.0"
skim = "0.9"
thiserror = "1.0"

# Clipboard support for non-X11
[target.'cfg(not(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")))))'.dependencies]
copypasta-ext = { version = "0.3.2", default-features = false, features = [] }

# Clipboard support for X11
[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")), not(target_env = "musl")))'.dependencies]
copypasta-ext = { version = "0.3.2", default-features = false, features = ["x11-fork"] }
x11-clipboard = "0.5"

# Clipboard support for X11 musl
[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")), target_env = "musl"))'.dependencies]
copypasta-ext = { version = "0.3.2", default-features = false, features = ["x11-bin"] }

[[bin]]
name = "prs"
path = "./src/main.rs"
