[package]
name = "prs-cli"
version = "0.1.0"
authors = ["Tim Visee <3a4fb3964f@sinenomine.email>"]
license = "GPL-3.0"
readme = "README.md"
# homepage = "https://timvisee.com/projects/prs"
repository = "https://gitlab.com/timvisee/prs"
description = "A smart and convenient pass client"
keywords = ["pass", "passwordstore"]
categories = [
    "authentication",
    "command-line-utilities",
    "cryptography",
]
edition = "2018"

[badges]
gitlab = { repository = "timvisee/prs", branch = "master" }

[dependencies]
anyhow = "1.0"
clap = "2.33"
colored = "2.0"
copypasta-ext = { version = "0.3.2", default-features = false, features = ["x11-fork"] }
derive_builder = "0.9"
prs-lib = { path = "../lib" }
shellexpand = "2.0"
skim = "0.8"
thiserror = "1.0"

[[bin]]
name = "prs"
path = "./src/main.rs"
