[package]
name = "prs-cli"
version = "0.1.4"
authors = ["Tim Visee <3a4fb3964f@sinenomine.email>"]
license = "GPL-3.0"
readme = "../README.md"
# homepage = "https://timvisee.com/projects/prs"
repository = "https://gitlab.com/timvisee/prs"
description = "Secure, fast & convenient password manager CLI with GPG & git sync"
keywords = ["pass", "passwordstore"]
categories = [
    "authentication",
    "command-line-utilities",
    "cryptography",
]
edition = "2018"

[badges]
gitlab = { repository = "timvisee/prs", branch = "master" }

[features]
default = ["clipboard", "notify"]

# Clipboard support
clipboard = ["copypasta-ext", "x11-clipboard", "base64"]

# Notification support (clipboard notifications)
notify = ["notify-rust"]

[dependencies]
anyhow = "1.0"
chbs = "0.1.0"
clap = "2.33"
colored = "2.0"
derive_builder = "0.9"
edit = "0.1"
libc = "0.2"
prs-lib = { version = "0.1.3", path = "../lib" }
shellexpand = "2.0"
skim = "0.9"
thiserror = "1.0"

# Notification support
notify-rust = { version = "4.0", optional = true }

# Clipboard support
base64 = { version = "0.13", optional = true }

# Clipboard support for non-X11
[target.'cfg(not(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")))))'.dependencies]
copypasta-ext = { version = "0.3.2", optional = true, default-features = false, features = [] }

# Clipboard support for X11
[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")), not(target_env = "musl")))'.dependencies]
copypasta-ext = { version = "0.3.2", optional = true, default-features = false, features = ["x11-fork"] }
x11-clipboard = { version = "0.5", optional = true }

# Clipboard support for X11 musl
[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")), target_env = "musl"))'.dependencies]
copypasta-ext = { version = "0.3.2", optional = true, default-features = false, features = ["x11-bin"] }

[[bin]]
name = "prs"
path = "./src/main.rs"
