[package]
name = "prs-cli"
version = "0.2.2"
authors = ["Tim Visee <3a4fb3964f@sinenomine.email>"]
license = "GPL-3.0"
readme = "../README.md"
homepage = "https://timvisee.com/projects/prs"
repository = "https://gitlab.com/timvisee/prs"
description = "Secure, fast & convenient password manager CLI with GPG & git sync"
keywords = ["pass", "passwordstore"]
categories = [
    "authentication",
    "command-line-utilities",
    "cryptography",
]
edition = "2018"
default-run = "prs"

[badges]
gitlab = { repository = "timvisee/prs", branch = "master" }

[features]
default = ["backend-gnupg-bin", "alias", "clipboard", "notify"]

# Backend using GPGME for GnuPG crypto
backend-gpgme = ["prs-lib/backend-gpgme"]

# Backend using GnuPG binary for GnuPG crypto
backend-gnupg-bin = ["prs-lib/backend-gnupg-bin"]

# Alias management (symlink) support, still follows symlinks if disables
# Automatically enabled for Unix and Windows targets
alias = []

# Clipboard support
clipboard = ["copypasta-ext", "x11-clipboard", "base64"]

# Notification support (clipboard notifications)
notify = ["notify-rust"]

[dependencies]
ansi-escapes = "0.1"
anyhow = "1.0"
chbs = "0.1.0"
clap = "2.33"
colored = "2.0"
derive_builder = "0.9"
edit = "0.1"
libc = "0.2"
prs-lib = { version = "0.2.2", path = "../lib", default-features = false }
rand = "0.8"
text_trees = "0.1"
thiserror = "1.0"
walkdir = "2.0"

# Notification support
notify-rust = { version = "4.0", optional = true }

# Clipboard support
base64 = { version = "0.13", optional = true }

# Vendored shellexpand fork until crate is updated
# See ./src/vendor/shellexpand.rs
# When removing, keep dirs-next, but only for Windows
dirs-next = "2.0"
# shellexpand = { version = "*", git = "https://github.com/timvisee/shellexpand.git", branch = "windows-paths" }

# Clipboard support for non-X11/Wayland
[target.'cfg(not(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")))))'.dependencies]
copypasta-ext = { version = "0.3.4", optional = true, default-features = false, features = [] }

# Clipboard support for X11/Wayland
[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")), not(target_env = "musl")))'.dependencies]
copypasta-ext = { version = "0.3.4", optional = true, default-features = false, features = ["x11-fork", "wayland-bin"] }
x11-clipboard = { version = "0.5", optional = true }

# Clipboard support for X11/Wayland musl
[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten")), target_env = "musl"))'.dependencies]
copypasta-ext = { version = "0.3.4", optional = true, default-features = false, features = ["x11-bin", "wayland-bin"] }

# Interactive selection with skim on unix platforms
[target.'cfg(unix)'.dependencies]
skim = "0.9"

[[bin]]
name = "prs"
path = "./src/main.rs"
