[package]
name = "prs-gtk3"
version = "0.2.2"
authors = ["Tim Visee <3a4fb3964f@sinenomine.email>"]
license = "GPL-3.0"
readme = "../README.md"
homepage = "https://timvisee.com/projects/prs"
repository = "https://gitlab.com/timvisee/prs"
description = "Secure, fast & convenient password manager CLI with GPG & git sync"
keywords = ["pass", "passwordstore"]
categories = [
    "authentication",
    "command-line-utilities",
    "cryptography",
]
edition = "2018"

[badges]
gitlab = { repository = "timvisee/prs", branch = "master" }

[features]
default = ["backend-gnupg-bin", "notify"]

# Backend using GPGME for GnuPG crypto
backend-gpgme = ["prs-lib/backend-gpgme"]

# Backend using GnuPG binary for GnuPG crypto
backend-gnupg-bin = ["prs-lib/backend-gnupg-bin"]

# Notification support (clipboard notifications)
notify = ["notify-rust"]

[dependencies]
anyhow = "1.0"
gdk = "^0"
gio = { version = "^0", features = ["v2_44"] }
glib = "^0"
gtk = { version = "0.9.0", features = ["v3_16"] }
prs-lib = { version = "0.2.2", path = "../lib", default-features = false }
thiserror = "1.0"

# Notification support
notify-rust = { version = "4.0", optional = true }

[[bin]]
name = "prs-gtk3-copy"
path = "./src/main.rs"
